import type { Metadata } from "next";
import "./globals.css";
import { Provider as JotaiProvider } from "jotai";
import { JotaiInitializer } from "@/components/layouts/JotaiInitializer";
import { HeaderWrapper } from "@/components/layouts/HeaderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <JotaiProvider>
          <JotaiInitializer />
          <HeaderWrapper />
          {children}
        </JotaiProvider>
      </body>
    </html>
  );
}
